# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('id_int', models.AutoField(primary_key=True, serialize=False)),
                ('name_text', models.CharField(max_length=200)),
                ('code_text', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentState',
            fields=[
                ('id_int', models.AutoField(primary_key=True, serialize=False)),
                ('priority', models.IntegerField(default=0)),
                ('lastChanged_datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LocationCondition',
            fields=[
                ('id_int', models.AutoField(primary_key=True, serialize=False)),
                ('longitude_dec', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude_dec', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_miles', models.FloatField()),
                ('priority', models.IntegerField(default=0)),
                ('clock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clock.Clock')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id_int', models.AutoField(primary_key=True, serialize=False)),
                ('name_text', models.CharField(max_length=200)),
                ('position_int', models.IntegerField(default=0)),
                ('clock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clock.Clock')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(null=True, upload_to=b'')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='locationcondition',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clock.State'),
        ),
        migrations.AddField(
            model_name='locationcondition',
            name='userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_location_condition', to='clock.UserProfile'),
        ),
        migrations.AddField(
            model_name='currentstate',
            name='clock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clock.UserProfile'),
        ),
        migrations.AddField(
            model_name='currentstate',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clock.State'),
        ),
        migrations.AddField(
            model_name='currentstate',
            name='userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_state', to='clock.UserProfile'),
        ),
        migrations.AddField(
            model_name='clock',
            name='userProfiles',
            field=models.ManyToManyField(related_name='users_clock', to='clock.UserProfile'),
        ),
    ]
