# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0003_auto_20170218_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='displayName_text',
            field=models.CharField(default='Brandon Goren', max_length=200),
            preserve_default=False,
        ),
    ]
