# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0005_remove_locationcondition_clock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationcondition',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
