# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0006_auto_20170218_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatarSource_text',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='currentstate',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_state_to_state', to='clock.State'),
        ),
        migrations.AlterField(
            model_name='locationcondition',
            name='userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_locationCondition', to='clock.UserProfile'),
        ),
    ]
