# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0007_auto_20170305_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clock',
            old_name='id_int',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='currentstate',
            old_name='id_int',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='currentstate',
            old_name='lastChanged_datetime',
            new_name='last_changed_datetime',
        ),
        migrations.RenameField(
            model_name='locationcondition',
            old_name='id_int',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='id_int',
            new_name='id',
        ),
    ]
