# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0009_auto_20170305_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clock',
            old_name='code_text',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='clock',
            old_name='name_text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='locationcondition',
            old_name='latitude_dec',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='locationcondition',
            old_name='longitude_dec',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='name_text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='position_int',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='display_name_text',
            new_name='display_name',
        ),
        migrations.RemoveField(
            model_name='currentstate',
            name='last_changed_datetime',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar_source_text',
        ),
        migrations.AddField(
            model_name='currentstate',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
