# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0010_auto_20170506_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clock',
            old_name='userProfiles',
            new_name='user_profiles',
        ),
        migrations.RenameField(
            model_name='currentstate',
            old_name='userProfile',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='locationcondition',
            old_name='userProfile',
            new_name='user_profile',
        ),
        migrations.AddField(
            model_name='clock',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
